### ISSUE TITLE
The difference between DTW_FUll and DTW_FULL_DTWCO

### ISSUE THREAD

**Issue by peter943** [TideDancer/DTWNet#6]
Hi,
Thanks again for your code. I have a question about the difference between DTW_FUll and DTW_FULL_DTWCO. Is the computing speed of the two algorithms very different? I found DTW_FULL uses '.so' file, but DTW_FULL_DTWCO does not.  I can run config_sliding.py when dtw_model is 'DTW_FULL_DTWCO'. But when dtw_model is 'DTW_FULL', there are some mistakes. I do not know if that is normal? Could you please give me some help? Thanks a lot.

**Comment by TideDancer** [comment]
DTW_FULL_DTWCO is directly using another repository https://github.com/lukauskas/dtwco. It performs DTW forward computation in an efficient manner. So it is easier to use that. The DTW_FULL use the custom code, that requires the deprecated pytorch c extension to build. Unless you need to customize the backward computation, which needs to write your own cuda code, you can simply use DTWCO to obtain the DTW path and perform back propogation based on the path.

**Comment by peter943** [comment]
@TideDancer Thanks for your patient reply.  In my understanding, it means that the results of DTW_CO and DTW_FULL should be same. 
I try to achieve a DTWNet for classification. I guess  if I want to replace the traditional conv kernel by the DTW kernel for CNN, I should use the DTWLAYER_SHORTKERNEL.  Because the DTW is based on the dynamic programming,  the computational complexity of DTW kernel is higher than traditional conv. I do not know if there is a good way to solve it when the number of kernel is large. Could you please give me some help? Thanks a lot.

**Comment by TideDancer** [comment]
That is a good question. Yes the DTW computation complexity is much higher. More importantly it is not easy to parallelize. I only tried very small DTW kernels. To achieve fast computation, I would suggest approximate DTW, e.g. band-constrained DTW, which runs in O(N) instead of O(N^2). Besides, I think to implement a low-level c++ code for backward computation should help a lot. I am not familiar with cuda coding so I didn't implement this part. Hope these helps.

**Comment by peter943** [comment]
I see. Thanks again for your kind help.
